import { useEffect, useState } from 'react'
import { motion } from 'framer-motion'
import { ArrowUp, Mail } from 'lucide-react'
import { personalData } from '../data/portfolioData'

export default function Footer() {
  const [showTop, setShowTop] = useState(false)
  useEffect(() => { const onScroll = () => setShowTop(window.scrollY > 400); window.addEventListener('scroll', onScroll, { passive: true }); return () => window.removeEventListener('scroll', onScroll) }, [])
  return <footer className="border-t" style={{ background: 'var(--bg-secondary)' }}><div className="mx-auto flex max-w-6xl flex-col items-center gap-5 px-6 py-10 text-center sm:flex-row sm:justify-between sm:text-left"><div><p className="font-mono text-sm accent-text">&lt;RTB /&gt;</p><p className="mt-2 text-xs text-muted">Built with Java-minded precision.</p></div><div className="flex items-center gap-2"><a href={personalData.github} target="_blank" rel="noopener noreferrer" aria-label="GitHub" className="flex h-11 w-11 items-center justify-center rounded-lg text-muted transition-all hover:-translate-y-1 hover:accent-text"><span className="font-mono text-xs font-semibold">GH</span></a><a href={personalData.linkedin} target="_blank" rel="noopener noreferrer" aria-label="LinkedIn" className="flex h-11 w-11 items-center justify-center rounded-lg text-muted transition-all hover:-translate-y-1 hover:accent-text"><span className="font-mono text-xs font-semibold">in</span></a><a href={`mailto:${personalData.email}`} aria-label="Email" className="flex h-11 w-11 items-center justify-center rounded-lg text-muted transition-all hover:-translate-y-1 hover:accent-text"><Mail size={18} /></a></div><p className="text-xs text-muted">© {new Date().getFullYear()} Rahul Tekchand Bainade</p></div><motion.button initial={{ opacity: 0, y: 20 }} animate={{ opacity: showTop ? 1 : 0, y: showTop ? 0 : 20, pointerEvents: showTop ? 'auto' : 'none' }} onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })} className="fixed bottom-6 right-6 z-40 flex h-12 w-12 items-center justify-center rounded-full accent-bg text-white shadow-lg shadow-emerald-500/20" aria-label="Back to top"><ArrowUp size={19} /></motion.button></footer>
}
