import {
  Code2,
  Database,
  Cloud,
  Wrench,
  Brain,
  Layers,
  Mail,
  Phone,
  type LucideIcon,
} from 'lucide-react'

export const personalData = {
  name: 'Rahul Tekchand Bainade',
  title: 'Full Stack Java Developer',
  email: 'rahulrajput79800@gmail.com',
  phone: '+91 7020495451',
  linkedin: 'https://www.linkedin.com/in/rahul-bainade-919985327/',
  github: 'https://github.com/Rahulrajput70202',
}

export const aboutText = [
  "I'm a Full Stack Java Developer who builds end-to-end web applications with Spring Boot, Spring Security, and Hibernate. My work spans REST APIs, JWT authentication, and database design — I care about writing code that's secure, maintainable, and actually solves the problem at hand.",
  "Recently I've been diving deep into AI-assisted applications. I built a RAG-powered Resume Matcher that combines traditional keyword matching with vector-based semantic retrieval using Spring AI, Ollama, and PostgreSQL with pgvector. It extracts text from PDFs, generates 768-dimensional embeddings, and uses vector similarity search to find the most relevant resume sections for a given job description.",
  "I'm comfortable across the full stack — from designing database schemas and writing clean backend logic to building responsive frontends with HTML, CSS, and JavaScript. I'm looking for a Full Stack Java Developer role where I can build scalable, secure, and intelligent web applications.",
]

export interface SkillCategory {
  title: string
  icon: LucideIcon
  skills: string[]
}

export const skillCategories: SkillCategory[] = [
  {
    title: 'Languages',
    icon: Code2,
    skills: ['Java', 'SQL', 'JavaScript', 'HTML5', 'CSS3'],
  },
  {
    title: 'Frameworks & Libraries',
    icon: Layers,
    skills: ['Spring Boot', 'Spring Security', 'Spring AI', 'Hibernate/JPA', 'Apache PDFBox', 'Java Swing'],
  },
  {
    title: 'AI & RAG',
    icon: Brain,
    skills: ['Ollama', 'Embeddings', 'Semantic Search', 'RAG', 'Vector Search'],
  },
  {
    title: 'Databases',
    icon: Database,
    skills: ['PostgreSQL', 'pgvector', 'MySQL', 'H2'],
  },
  {
    title: 'Cloud',
    icon: Cloud,
    skills: ['AWS (EC2, S3)'],
  },
  {
    title: 'Tools',
    icon: Wrench,
    skills: ['Git', 'GitHub', 'Maven', 'Postman', 'IntelliJ IDEA', 'Jira'],
  },
  {
    title: 'Concepts',
    icon: Layers,
    skills: [
      'OOP',
      'Collections Framework',
      'JDBC',
      'REST APIs',
      'JWT Authentication',
      'MVC Architecture',
      'CRUD Operations',
      'RAG Pipelines',
      'Vector Databases',
      'Exception Handling',
    ],
  },
]

export interface CoreStrength {
  name: string
  level: number
}

export const coreStrengths: CoreStrength[] = [
  { name: 'Java', level: 90 },
  { name: 'Spring Boot', level: 85 },
  { name: 'REST APIs', level: 88 },
]

export interface Project {
  title: string
  github: string
  tech: string[]
  highlights: string[]
  gradient: string
}

export const projects: Project[] = [
  {
    title: 'Resume Matcher — RAG-Powered Spring Boot Web App',
    github: 'https://github.com/Rahulrajput70202/resume-matcher',
    tech: ['Java', 'Spring Boot', 'Spring Security', 'PostgreSQL', 'pgvector', 'Ollama', 'Apache PDFBox', 'JWT', 'HTML/CSS/JS'],
    highlights: [
      'Built a full-stack RAG-powered Resume Matcher using Spring Boot, Spring Security, PostgreSQL with pgvector, and Ollama for AI-driven semantic search',
      'Upgraded keyword matching with semantic search using 768-dimensional embeddings generated by nomic-embed-text',
      'Implemented PDF text extraction and chunking with Apache PDFBox for efficient resume processing',
      'Combined keyword matching with vector similarity retrieval to identify matched and missing skills against job descriptions',
    ],
    gradient: 'from-emerald-500/20 to-blue-500/20',
  },
  {
    title: 'Store Management System — Java Swing Desktop App',
    github: 'https://github.com/Rahulrajput70202/java-store-management',
    tech: ['Java', 'Java Swing', 'DefaultTableModel'],
    highlights: [
      'Built a desktop inventory management app in Java Swing with a fully interactive GUI, automating CRUD operations across all inventory records',
      'Implemented add, update, delete, and search functionality using DefaultTableModel for dynamic, real-time table updates',
      'Developed a billing module with automatic itemized total calculation and editable rows, cutting manual calculation errors',
      'Roadmap: MySQL integration, PDF/Excel export, role-based login',
    ],
    gradient: 'from-amber-500/20 to-emerald-500/20',
  },
]

export interface ExperienceEntry {
  role: string
  company: string
  location: string
  remote: boolean
  dates: string
  bullets: string[]
}

export const experience: ExperienceEntry[] = [
  {
    role: 'Python Programming Intern',
    company: 'Vault of Codes',
    location: 'India',
    remote: true,
    dates: 'Aug 2025 – Sep 2025',
    bullets: [
      'Completed a 1-month internship building hands-on experience in Python programming, application logic, and structured problem-solving',
      'Applied core programming and OOP concepts to real-world project tasks, translating academic knowledge into working software',
      'Collaborated with a development team, incorporating mentorship and code feedback into iterative improvements',
    ],
  },
]

export interface EducationEntry {
  degree: string
  cgpa: string
  college: string
  university: string
  location: string
  dates: string
}

export const education: EducationEntry = {
  degree: 'Bachelor of Computer Science',
  cgpa: '8.01',
  college: 'Dr. G.Y. Pathrikar College of CS & IT',
  university: 'MGM University',
  location: 'Chh. Sambhajinagar, India',
  dates: 'Jun 2023 – Jul 2026',
}

export const socialLinks = [
  { icon: Mail, label: 'Email', href: 'mailto:rahulrajput79800@gmail.com' },
  { icon: Phone, label: 'Phone', href: 'tel:+917020495451' },
]
